words = [
    "Affordances",
    "Breadboarding",
    "ELIXIRKIT",
    "LLC",
    "OTP",
    "Tauri",
    "Tradeoffs",
    "Zornek",
    "affordance",
    "afterend",
    "cli",
    "dialogs",
    "dialyxir",
    "elixirc",
    "exdoc",
    "livebook",
    "mockup",
    "mockups",
    "sobelow",
    "tailwindlabs",
]
